INSERT INTO LOCATION (BUILDING, FLOOR) VALUES ('Building#10', '3');
INSERT INTO LOCATION (BUILDING, FLOOR) VALUES ('Building#6', '4');
INSERT INTO LOCATION (BUILDING, FLOOR) VALUES ('Building#6', '3');
INSERT INTO LOCATION (BUILDING, FLOOR) VALUES ('Building#7', '3');
INSERT INTO LOCATION (BUILDING, FLOOR) VALUES ('Building#9', '7');
INSERT INTO LOCATION (BUILDING, FLOOR) VALUES ('Building#11', '5');
INSERT INTO LOCATION (BUILDING, FLOOR) VALUES ('Building#20', '2');

INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Nubra', 'available', '4', 4);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Auli', 'available', '8', 5);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Betaab', 'available', '8', 3);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Lug', 'available', '4', 3);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Kashmir', 'available', '4', 2);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Lidder', 'available', '8', 2);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Brahmaputra', 'available', '8', 1);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Breng', 'available', '4', 6);
INSERT INTO MEETING_ROOM ( NAME, STATUS, TYPE, LOCATION_ID) VALUES ('Bilaspur', 'available', '8', 7);